# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'

target 'InnovaZones' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])


#  pod 'React', :path => '../node_modules/react-native/'
#  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
#  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
# pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
#
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
#  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
#  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
   pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
#  pod 'RNFS', :path => '../node_modules/react-native-fs'
 #  pod 'React-Core', :path => '../node_modules/react-native/'
#pod 'react-native-webview', :path => '../node_modules/react-native-webview'

#   pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
#   'TextDetector',
#   'FaceDetectorMLKit',
#   'BarcodeDetectorMLKit'
# ]
#  pod 'AppCenter/Crashes', '~> 2.5.0'
#  pod 'AppCenter/Analytics', '~> 2.5.0'
  pod 'AppCenterReactNativeShared', '~> 2.5.0'
  pod 'SKTCaptureObjC', '~> 1.1'
   
   permissions_path = '../node_modules/react-native-permissions/ios'
     pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

#  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
#  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
#    use_flipper!
#    post_install do |installer|
#      flipper_post_install(installer)
#    end

# Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3',
  'Flipper' => '0.87.0','Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       installer.pods_project.build_configurations.each do |config|
       config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
  end
end
end


#use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
#  post_install do |installer|
#    react_native_post_install(installer)
#        installer.pods_project.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
#        end
#  end

#end
  target 'InnovaZonesTests' do
    inherit! :complete
    # Pods for testing
  end
  
  
 target 'InnovaZones-tvOS' do
   # Pods for RnDiffApp-tvOS
   target 'InnovaZones-tvOSTests' do
     inherit! :search_paths
     # Pods for testing
   end
 end



